# Generated by Django 3.0.5 on 2020-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=200)),
                ('book_subject', models.CharField(max_length=100)),
                ('book_quantity', models.IntegerField(default=10)),
            ],
        ),
    ]
