# Generated by Django 3.0.2 on 2020-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default='default.jpg', upload_to='book_pics'),
        ),
    ]
