# Generated by Django 3.0.5 on 2020-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='librarian_dob',
            field=models.DateField(default='2020-09-06'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_dob',
            field=models.DateField(default='2020-09-06'),
        ),
    ]
