# Generated by Django 3.0.5 on 2020-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200906_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_type',
            field=models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers')], default='Students', max_length=50),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='librarian_dob',
            field=models.DateField(default='2020-09-08'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_dob',
            field=models.DateField(default='2020-09-08'),
        ),
    ]
