# Generated by Django 3.0.2 on 2020-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_member_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='librarian_dob',
            field=models.DateField(default='2020-09-11'),
        ),
    ]
