# Generated by Django 3.0.2 on 2020-09-12 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200911_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_department',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='librarian',
            name='librarian_dob',
            field=models.DateField(default='2020-09-12'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Students', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
