# Generated by Django 3.0.2 on 2020-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200912_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX')], max_length=50),
        ),
    ]
