# Generated by Django 3.0.2 on 2020-10-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transactions', '0002_auto_20201016_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Transactions.Transaction')),
            ],
        ),
    ]
